### ISSUE TITLE
SRMD test images are BW even when  "n_channels": 3

### ISSUE THREAD

**Issue by ManoaNosea** [cszn/KAIR#10]
![a_lfwall16a_500](https://user-images.githubusercontent.com/7376591/76890804-b1747480-6890-11ea-8b48-db839e593ece.png)

**Comment by ManoaNosea** [comment]
the training goes normal but these are the test images

**Comment by ManoaNosea** [comment]
it was only at 500, gives the colors later, 1000 does, but still not using much the card

**Comment by cszn** [comment]
Change the setting https://github.com/cszn/KAIR/blob/6d4ff120435ca2e0f8d0cdfc8aa7e3c59f24d281/options/train_srmd.json#L4

**Comment by ManoaNosea** [comment]
I mean, it allocates memory to 2 giga on the card but the GPU load/usage is very low
I have "dataloader_batch_size": 256

**Comment by cszn** [comment]
https://github.com/xinntao/BasicSR/wiki/Prepare-datasets-in-LMDB-format
or use split_imageset(original_dataroot, taget_dataroot, n_channels=3, p_size=512, p_overlap=96, p_max=800) to get trainsets/trainH with small images for fast data loading

**Comment by ManoaNosea** [comment]
```
Traceback (most recent call last):
  File "main_train_dpsr.py", line 242, in <module>
    main()
  File "main_train_dpsr.py", line 109, in main
    train_set = define_Dataset(dataset_opt)
  File "F:\KAIR-master\data\select_dataset.py", line 56, in define_Dataset
    dataset = D(dataset_opt)
  File "F:\KAIR-master\data\dataset_dpsr.py", line 32, in __init__
    self.paths_H = util.get_image_paths(opt['dataroot_H'])
  File "F:\KAIR-master\utils\utils_image.py", line 69, in get_image_paths
    paths = sorted(_get_paths_from_images(dataroot))
  File "F:\KAIR-master\utils\utils_image.py", line 81, in _get_paths_from_images
    assert images, '{:s} has no valid image file'.format(path)
AssertionError: F:/DCSCNv2-2019/data/all/all-hr.lmdb has no valid image file
```

**Comment by ManoaNosea** [comment]
it look like he doesn't understand this format :x

**Comment by yucongzhao1** [comment]
@ManoaNosea SRMD training is almost not using the card，Have you solved it？

**Comment by ManoaNosea** [comment]
no, not yet :x

**Comment by taaa22** [comment]
@ManoaNosea 
have you solved it? it seems like we are facing the same problem,
the training is very slow even in Tesla V100 GPU
