### ISSUE TITLE
OST Dataset - stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by mushding** [cszn/KAIR#110]
Hi there, thanks for the amazing work!

I'm traning the SwinIR-classical model recently, according to SwinIR github page SwinIR-M traning dataset including DIV2K, Flickr2K.

but  I want  a larger dataset, so I add OST dataset in it.

but i got an error when execute main_train_psnr.py

```
<epoch:  0, iter:     860, lr:2.000e-04> G_loss: 4.096e-02 
---1-->   baby.png | 30.40dB
---2-->   bird.png | 27.21dB
---3--> butterfly.png | 21.32dB
---4-->   head.png | 28.58dB
---5-->  woman.png | 25.64dB
<epoch:  0, iter:     860, Average PSNR : 26.63dB

Traceback (most recent call last):
  File "main_train_psnr.py", line 275, in <module>
    main()
  File "main_train_psnr.py", line 183, in main
    for i, train_data in enumerate(train_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 24, 24] at entry 0 and [3, 24, 20] at entry 6
```

and my config file is

```json
, "datasets": {
    "train": {
      "name": "train_dataset"       
      , "dataset_type": "sr"      
      , "dataroot_H": "trainsets/trainH"   // include DIV2K, Flickr2K, OST  
      , "dataroot_L": null               

      , "H_size": 96           

      , "dataloader_shuffle": true
      , "dataloader_num_workers": 0
      , "dataloader_batch_size": 16      // batch size 1 | 16 | 32 | 48 | 64 | 128. Total batch size =4x8=32 in SwinIR
    }
    , "test": {
      "name": "test_dataset"            // just name
      , "dataset_type": "sr"         // "dncnn" | "dnpatch" | "fdncnn" | "ffdnet" | "sr" | "srmd" | "dpsr" | "plain" | "plainpatch" | "jpeg"
      , "dataroot_H": "testsets/Set5/GTmod12"    
      , "dataroot_L": "testsets/Set5/LRbicx4"                 // path of L testing dataset 
    }
  }
```

why adding OST dataset will get this error?

**Comment by JingyunLiang** [comment]
I am not sure. Adding OST dataset should have no problem, as we also use OST in real-world image SR. As for the error, it's because some images are too small to crop a 96x96 patch.
