### ISSUE TITLE
Sizes of tensors must match except in dimension 0. Got 24 and 8 in dimension 3

### ISSUE THREAD

**Issue by ManoaNosea** [cszn/KAIR#13]
```
 |  0.000 | -0.029 |  0.021 |  0.007 || model.10.weight

Traceback (most recent call last):
  File "main_train_dpsr.py", line 242, in <module>
    main()
  File "main_train_dpsr.py", line 149, in main
    for i, train_data in enumerate(train_loader):
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\_utils\collate.py", line 75, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\_utils\collate.py", line 75, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\utils\data\_utils\collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 24 and 8 in dimension 3 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689
```
this is happened after adding more files to dataset, it doesn't say which file is the problem :x

**Comment by ManoaNosea** [comment]
the problem is he doesn't say which file is the problem

**Comment by cszn** [comment]
Some of your training images have a smaller size than the patch size.
