### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by ManoaNosea** [cszn/KAIR#14]
during inference of some pictures, it gives this error:
```
F:\KAIR-master
λ python main_test_msrresnet.py
LogHandlers setup!
20-03-28 18:57:42.765 : Model path: model_zoo\msrresnet_x4_gan.pth
20-03-28 18:57:42.765 : Params number: 1517571
20-03-28 18:57:42.765 : model_name:msrresnet_x4_gan, image sigma:0
20-03-28 18:57:42.765 : testsets\input
Traceback (most recent call last):
  File "main_test_msrresnet.py", line 213, in <module>
    main()
  File "main_test_msrresnet.py", line 161, in main
    img_E = model(img_L)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\KAIR-master\models\network_msrresnet.py", line 127, in forward
    out = self.lrelu(self.pixel_shuffle(self.upconv2(out)))
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
I tested 2 cudnn DLL they both give the error

**Comment by ManoaNosea** [comment]
DPSR too:
```
F:\KAIR-master
λ python main_test_dpsr.py
LogHandlers setup!
20-03-28 18:17:57.163 : Model path: model_zoo\dpsr_x4.pth
20-03-28 18:17:57.163 : Params number: 3493824
20-03-28 18:17:57.163 : model_name:dpsr_x4, model sigma:0, image sigma:0
20-03-28 18:17:57.163 : testsets\input
Traceback (most recent call last):
  File "main_test_dpsr.py", line 214, in <module>
    main()
  File "main_test_dpsr.py", line 162, in main
    img_E = model(img_L)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\KAIR-master\models\network_dpsr.py", line 74, in forward
    x = self.model(x)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
