### ISSUE TITLE
main_test_rrdb.py

### ISSUE THREAD

**Issue by House-Leo** [cszn/KAIR#25]
用main_train_rrdb_psnr.py训练出model之后，用test代码不能正常超分图片。
用原model = net(in_nc=3, out_nc=3, nc=64, nb=23, gc=32, upscale=4, act_mode='L', upsample_mode='upconv')
得出的输出会变黄色，后面按照option改成了
model = net(in_nc=3, out_nc=3, nc=64, nb=23, gc=32, upscale=4, act_mode='R', upsample_mode='upconv')
得出的输出会变黑色
训练过程中的验证是能正常超分出来的

**Comment by cszn** [comment]
再检查一下.

**Comment by House-Leo** [comment]
@cszn 改成True后，提示以下错误
Traceback (most recent call last):
  File "main_test_rrdb.py", line 162, in <module>
    main()
  File "main_test_rrdb.py", line 62, in main
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/public_files/software/envs/mmsr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RRDB:
	Missing key(s) in state_dict: "model.6.weight", "model.6.bias", "model.8.weight", "model.8.bias", "model.10.weight", "model.10.bias". 
	Unexpected key(s) in state_dict: "model.5.weight", "model.5.bias", "model.7.weight", "model.7.bias".
