### ISSUE TITLE
decompressing data: inconsistent stream state

### ISSUE THREAD

**Issue by clttyou** [cszn/KAIR#53]
Hello, I'm in python main_test_usrnet.py encountered
Traceback (most recent call last):
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/hdf5storage/init.py", line 1768, in loadmat
with h5py.File(filename, mode='r') as f:
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in init
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (File signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main_test_table1.py", line 230, in
main()
File "main_test_table1.py", line 87, in main
kernels = hdf5storage.loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/hdf5storage/init.py", line 1801, in loadmat
**keywords)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 208, in loadmat
matfile_dict = MR.get_variables(variable_names)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 272, in get_variables
hdr, next_position = self.read_var_header()
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 226, in read_var_header
mdtype, byte_count = self._matrix_reader.read_full_tag()
File "mio5_utils.pyx", line 548, in scipy.io.matlab.mio5_utils.VarReader5.read_full_tag
File "mio5_utils.pyx", line 556, in scipy.io.matlab.mio5_utils.VarReader5.cread_full_tag
File "streams.pyx", line 171, in scipy.io.matlab.streams.ZlibInputStream.read_into
File "streams.pyx", line 158, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -2 while decompressing data: inconsistent stream state
My environment：
h5py 2.7.0
hdf5storage 0.1.15
torch 1.6.0+cu92
torchvision 0.7.0+cu92
Have you ever encounterd such a problem? Thank you very much.

您好，我在python main_test_usrnet.py遇到
Traceback (most recent call last):
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/hdf5storage/init.py", line 1768, in loadmat
with h5py.File(filename, mode='r') as f:
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in init
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (File signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main_test_table1.py", line 230, in
main()
File "main_test_table1.py", line 87, in main
kernels = hdf5storage.loadmat(os.path.join('kernels', 'kernels_12.mat'))['kernels']
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/hdf5storage/init.py", line 1801, in loadmat
**keywords)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 208, in loadmat
matfile_dict = MR.get_variables(variable_names)
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 272, in get_variables
hdr, next_position = self.read_var_header()
File "/root/userfolder/anaconda3/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 226, in read_var_header
mdtype, byte_count = self._matrix_reader.read_full_tag()
File "mio5_utils.pyx", line 548, in scipy.io.matlab.mio5_utils.VarReader5.read_full_tag
File "mio5_utils.pyx", line 556, in scipy.io.matlab.mio5_utils.VarReader5.cread_full_tag
File "streams.pyx", line 171, in scipy.io.matlab.streams.ZlibInputStream.read_into
File "streams.pyx", line 158, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -2 while decompressing data: inconsistent stream state

我的环境
h5py 2.7.0
hdf5storage 0.1.15
torch 1.6.0+cu92
torchvision 0.7.0+cu92
请问有遇到过这种问题吗？十分感谢

**Comment by clttyou** [comment]
The problem has been solved
