### ISSUE TITLE
how do you do inference on trained model ?

### ISSUE THREAD

**Issue by ManoaNosea** [cszn/KAIR#8]
```
F:\KAIR-master
? python main_test_msrresnet.py
LogHandlers setup!
20-03-05 11:08:56.303 : Model path: superresolution/msrresnet_gan/models\10000_G.pth
20-03-05 11:08:56.319 : Params number: 1517571
20-03-05 11:08:56.319 : model_name:10000_G, image sigma:0
20-03-05 11:08:56.319 : testsets\set5
Traceback (most recent call last):
  File "main_test_msrresnet.py", line 213, in <module>
    main()
  File "main_test_msrresnet.py", line 146, in main
    img_L = util.imresize_np(img_L, 1/sf)
  File "F:\KAIR-master\utils\utils_image.py", line 859, in imresize_np
    in_H, out_H, scale, kernel, kernel_width, antialiasing)
  File "F:\KAIR-master\utils\utils_image.py", line 756, in calculate_weights_indices
    sym_len_s = -indices.min() + 1
RuntimeError: invalid argument 1: cannot perform reduction function min on tensor with no elements because the operation does not have an identity at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:164
```

**Comment by ManoaNosea** [comment]
```
F:\KAIR-master
? python main_test_msrresnet.py
LogHandlers setup!
Traceback (most recent call last):
  File "main_test_msrresnet.py", line 213, in <module>
    main()
  File "main_test_msrresnet.py", line 112, in main
    model.load_state_dict(torch.load(model_path), strict=True)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MSRResNet1:
        Missing key(s) in state_dict: "conv_first.weight", "conv_first.bias", "recon_trunk.0.conv1.weight", "recon_trunk.0.conv1.bias", "recon_trunk.0.conv2.weight", "recon_trunk.0.conv2.bias", "recon_trunk.1.conv1.weight", "recon_trunk.1.conv1.bias", "recon_trunk.1.conv2.weight", "recon_trunk.1.conv2.bias", "recon_trunk.2.conv1.weight", "recon_trunk.2.conv1.bias", "recon_trunk.2.conv2.weight", "recon_trunk.2.conv2.bias", "recon_trunk.3.conv1.weight", "recon_trunk.3.conv1.bias", "recon_trunk.3.conv2.weight", "recon_trunk.3.conv2.bias", "recon_trunk.4.conv1.weight", "recon_trunk.4.conv1.bias", "recon_trunk.4.conv2.weight", "recon_trunk.4.conv2.bias", "recon_trunk.5.conv1.weight", "recon_trunk.5.conv1.bias", "recon_trunk.5.conv2.weight", "recon_trunk.5.conv2.bias", "recon_trunk.6.conv1.weight", "recon_trunk.6.conv1.bias", "recon_trunk.6.conv2.weight", "recon_trunk.6.conv2.bias", "recon_trunk.7.conv1.weight", "recon_trunk.7.conv1.bias", "recon_trunk.7.conv2.weight", "recon_trunk.7.conv2.bias", "recon_trunk.8.conv1.weight", "recon_trunk.8.conv1.bias", "recon_trunk.8.conv2.weight", "recon_trunk.8.conv2.bias", "recon_trunk.9.conv1.weight", "recon_trunk.9.conv1.bias", "recon_trunk.9.conv2.weight", "recon_trunk.9.conv2.bias", "recon_trunk.10.conv1.weight", "recon_trunk.10.conv1.bias", "recon_trunk.10.conv2.weight", "recon_trunk.10.conv2.bias", "recon_trunk.11.conv1.weight", "recon_trunk.11.conv1.bias", "recon_trunk.11.conv2.weight", "recon_trunk.11.conv2.bias", "recon_trunk.12.conv1.weight", "recon_trunk.12.conv1.bias", "recon_trunk.12.conv2.weight", "recon_trunk.12.conv2.bias", "recon_trunk.13.conv1.weight", "recon_trunk.13.conv1.bias", "recon_trunk.13.conv2.weight", "recon_trunk.13.conv2.bias", "recon_trunk.14.conv1.weight", "recon_trunk.14.conv1.bias", "recon_trunk.14.conv2.weight", "recon_trunk.14.conv2.bias", "recon_trunk.15.conv1.weight", "recon_trunk.15.conv1.bias", "recon_trunk.15.conv2.weight", "recon_trunk.15.conv2.bias", "upconv1.weight", "upconv1.bias", "upconv2.weight", "upconv2.bias", "HRconv.weight", "HRconv.bias", "conv_last.weight", "conv_last.bias".
        Unexpected key(s) in state_dict: "features.0.weight", "features.0.bias", "features.1.weight", "features.1.bias", "features.2.weight", "features.2.bias", "features.2.running_mean", "features.2.running_var", "features.2.num_batches_tracked", "features.4.weight", "features.4.bias", "features.5.weight", "features.5.bias", "features.5.running_mean", "features.5.running_var", "features.5.num_batches_tracked", "features.7.weight", "features.7.bias", "features.8.weight", "features.8.bias", "features.8.running_mean", "features.8.running_var", "features.8.num_batches_tracked", "features.10.weight", "features.10.bias", "features.11.weight", "features.11.bias", "features.11.running_mean", "features.11.running_var", "features.11.num_batches_tracked", "features.13.weight", "features.13.bias", "features.14.weight", "features.14.bias", "features.14.running_mean", "features.14.running_var", "features.14.num_batches_tracked", "features.16.weight", "features.16.bias", "features.17.weight", "features.17.bias", "features.17.running_mean", "features.17.running_var", "features.17.num_batches_tracked", "features.19.weight", "features.19.bias", "features.20.weight", "features.20.bias", "features.20.running_mean", "features.20.running_var", "features.20.num_batches_tracked", "features.22.weight", "features.22.bias", "features.23.weight", "features.23.bias", "features.23.running_mean", "features.23.running_var", "features.23.num_batches_tracked", "features.25.weight", "features.25.bias", "features.26.weight", "features.26.bias", "features.26.running_mean", "features.26.running_var", "features.26.num_batches_tracked", "classifier.0.weight", "classifier.0.bias", "classifier.2.weight", "classifier.2.bias".
```

**Comment by ManoaNosea** [comment]
it appears to be working after I disabled degradation and set H to None ?
