### ISSUE TITLE
When test using my model, I met mismatch error.

### ISSUE THREAD

**Issue by edwardcho** [cszn/KAIR#90]
Hello Sir,

I trained my data using DnCNN model.

```
# my option config file.

  , "train": {
    "G_lossfn_type": "l1"               // "l1" preferred | "l2sum" | "l2" | "ssim"
    , "G_lossfn_weight": 1.0            // default

    , "G_optimizer_type": "adam"        // fixed, adam is enough
    , "G_optimizer_lr": 1e-4            // learning rate
    , "G_optimizer_clipgrad": null      // unused

    , "G_scheduler_type": "MultiStepLR" // "MultiStepLR" is enough
    , "G_scheduler_milestones": [200000, 400000, 600000, 800000, 1000000, 2000000]
    , "G_scheduler_gamma": 0.5

    , "G_regularizer_orthstep": null    // unused
    , "G_regularizer_clipstep": null    // unused

    , "checkpoint_test": 500           // for testing
    , "checkpoint_save": 500           // for saving model
    , "checkpoint_print": 200           // for print
  }

```

After progress training, I checked some model files.
    500_G.pth
   1000_G.pth

Then, for testing.
I modified model_path in your code (main_test_dncnn.py).

```
#model_path = os.path.join(args.model_pool, args.model_name+'.pth')
model_path = '500_G.pth'
```

Then,
I met some mismatch message.
```
/data1/TESTBOARD/additional_networks/denoising/KAIR/savepath_models/dncnn25/models/500_G.pth
LogHandlers setup!
Traceback (most recent call last):
  File "main_test_dncnn.py", line 207, in <module>
    main()
  File "main_test_dncnn.py", line 125, in main
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/home/myhome/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DnCNN:
        Missing key(s) in state_dict: "model.4.weight", "model.4.bias", "model.10.weight", "model.10.bias", "model.16.weight", "model.16.bias", "model.22.weight", "model.22.bias", "model.28.weight", "model.28.bias".
        Unexpected key(s) in state_dict: "model.33.weight", "model.33.bias", "model.33.running_mean", "model.33.running_var", "model.33.num_batches_tracked", "model.35.weight", "model.35.bias", "model.36.weight", "model.36.bias", "model.36.running_mean", "model.36.running_var", "model.36.num_batches_tracked", "model.38.weight", "model.38.bias", "model.39.weight", "model.39.bias", "model.39.running_mean", "model.39.running_var", "model.39.num_batches_tracked", "model.41.weight", "model.41.bias", "model.42.weight", "model.42.bias", "model.42.running_mean", "model.42.running_var", "model.42.num_batches_tracked", "model.44.weight", "model.44.bias", "model.45.weight", "model.45.bias", "model.45.running_mean", "model.45.running_var", "model.45.num_batches_tracked", "model.47.weight", "model.47.bias", "model.3.weight", "model.3.bias", "model.3.running_mean", "model.3.running_var", "model.3.num_batches_tracked", "model.5.weight", "model.5.bias", "model.6.running_mean", "model.6.running_var", "model.6.num_batches_tracked", "model.9.weight", "model.9.bias", "model.9.running_mean", "model.9.running_var", "model.9.num_batches_tracked", "model.11.weight", "model.11.bias", "model.12.running_mean", "model.12.running_var", "model.12.num_batches_tracked", "model.15.weight", "model.15.bias", "model.15.running_mean", "model.15.running_var", "model.15.num_batches_tracked", "model.17.weight", "model.17.bias", "model.18.running_mean", "model.18.running_var", "model.18.num_batches_tracked", "model.21.weight", "model.21.bias", "model.21.running_mean", "model.21.running_var", "model.21.num_batches_tracked", "model.23.weight", "model.23.bias", "model.24.running_mean", "model.24.running_var", "model.24.num_batches_tracked", "model.27.weight", "model.27.bias", "model.27.running_mean", "model.27.running_var", "model.27.num_batches_tracked", "model.29.weight", "model.29.bias", "model.30.running_mean", "model.30.running_var", "model.30.num_batches_tracked".
        size mismatch for model.6.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for model.12.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for model.18.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for model.24.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for model.30.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for model.32.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 64, 3, 3]).
        size mismatch for model.32.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([1]).

```

I don't know that reason.
For solving, What should I do ??

Thanks,

**Comment by IvanGarcia7** [comment]
@edwardcho how did you solve that? I'm fancing the same problem

**Comment by edwardcho** [comment]
> @edwardcho how did you solve that? I have the same problem

I just changed act_mode. 
In my code, act_mode is 'BR'.
